### ISSUE TITLE
[Bug]: empty day is skipped when start_day is static

### ISSUE THREAD

**Issue by sundar2012** [alexpfau/calendar-card-pro#160]
### Requirements

- [x] I've checked that I'm using the latest version of Calendar Card Pro
- [x] I've searched existing issues to verify this isn't a duplicate
- [x] I've tried refreshing with a cleared browser cache (Ctrl+F5 or Cmd+Shift+R)

### Current Behavior

If a calendar has no events to show on a day but the start_date is static and the days_to_show is 1, it will skip and show the next day with an event rather than show "no upcoming events"

### Expected Behavior

the calendar should show "no upcoming events"

### Steps To Reproduce

Create a calendar with the following events:

2024-04-07: no events
2024-04-08: an event 

then create a calendar-card-pro with the following yaml:

```
type: custom:calendar-card-pro
entities:
  - entity: calendar.my_calendar
start_date: '2025-04-07'
days_to_show: 1

```

You will see it will show essentially 2025-04-08 because its the first day with an event even though the card is configured to show only '2025-04-07'

### Card Configuration

```yaml
type: custom:calendar-card-pro
entities:
  - entity: calendar.my_calendar
start_date: '2025-04-07'
days_to_show: 1
'''
```

### Calendar Entity State

```yaml
message: "placeholder"
all_day: false
start_time: "2025-04-08 18:00:00"
end_time: "2025-04-08 19:00:00"
location: ""
description: ""
friendly_name: my_calendar
```

### Browser Console Logs

```shell

```

### Environment

```markdown
- Browser & Version: 
- Home Assistant Version: 
- Calendar Card Pro Version: 
- Device Type:
```

### Additional Information

the solution should probably be a flag for "skip_empty_days" that defaults to true which is the current behavior.  when set to false, empty days are displayed with a "no events found".

**Comment by alexpfau** [comment]
Wow, good catch! Thanks! I have just implemented a fix.

**Comment by sundar2012** [comment]
@alexpfau Im still encountering this issue on v2.4.1 .  Let me know what you might need to debug.  YAML in question is:

```
type: custom:calendar-card-pro
entities:
  - entity: calendar.family_calendar
    allowlist: Susie|Sooz|susie|sooz|Kenzie|kenzie|date|Date|Sitter|sitter
  - entity: calendar.home
    allowlist: Susie|Sooz|susie|sooz||Kenzie|kenzie|date|Date|Sitter|sitter
days_to_show: 1
start_date: today
show_location: false
show_current_week_number: false
show_month: false
card_mod:
  style: |
    ha-card {
      width: 115%;
      left: -55%;
      .date-column {
          display: none;
      }
    }
show_past_events: true

```

Both filtered entities return no events for "today" but the card is rendering events from the next day.

**Comment by alexpfau** [comment]
@sundar2012, I probably misunderstood your bug ticket at first. What you describe is intended behavior! Configuring the card with `days_to_show: 1` means the card will always show one day with events. If there are no events on the configured start_date, whether its today or any day in the future, it will show the next day after that with events. If you set `days_to_show: 2` then the card shows the next two days with events from the configured start_date - those could be the start_date and the day after, or a day 1y later and another day 2y later.

This is intended because my card is a **list view** and not a schedule view. Setting `days_to_show` means setting how many days with events your card is supposed to show.

Therefore, no bug here, but what you describe (if I understand correctly now) is intended behavior.

**Comment by alexpfau** [comment]
Should be fixed now with v2.4.3
